# docker-compose-azure.yml
version: '3'
services:
  frontend:
    image: <ACR_NAME>.azurecr.io/frontend:latest
    ports:
      - "80:80"         # expose port 80 externally (frontend is entrypoint)
    depends_on:
      - backend         # ensure backend starts before frontend
  backend:
    image: <ACR_NAME>.azurecr.io/backend:latest
    ports:
      - "8000:8000"     # optional: expose for clarity (not externally needed when proxied)
