name: Azure Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name visual --expose-token
          echo "::add-mask::$(az acr login --name visual --expose-token --output tsv --query accessToken)"
          docker login visual.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p $(az acr login --name visual --expose-token --output tsv --query accessToken)

      - name: Build and push frontend image
        run: |
          docker build -t visual.azurecr.io/frontend:latest ./frontend/
          docker push visual.azurecr.io/frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t visual.azurecr.io/backend:latest ./backend/
          docker push visual.azurecr.io/backend:latest

      - name: Deploy using docker-compose
        run: |
          az webapp config container set \
            --name ${{ secrets.APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --multicontainer-config-type compose \
            --multicontainer-config-file docker-compose-azure.yml \
            --docker-registry-server-url visual.azurecr.io \
            --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}