name: Azure Deployment

on:
  push:
    branches: [ main ]  # Specify which branch triggers the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: visual.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t visual.azurecr.io/frontend:latest ./frontend/
          docker push visual.azurecr.io/frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t visual.azurecr.io/backend:latest ./backend/
          docker push visual.azurecr.io/backend:latest

      - name: Deploy using docker-compose
        run: |
          az webapp config container set \
            --name ${{ secrets.APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --multicontainer-config-type compose \
            --multicontainer-config-file docker-compose-azure.yml \
            --docker-registry-server-url visual.azurecr.io \
            --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}